import { z } from "zod";
import { router, procedure } from "@/trpc";
import {
  recipeSchema,
  createRecipeInput,
  updateRecipeInput,
} from "@/types/recipe";
import { recipeRepository } from "@/storage/recipes";
import {
  settingsSchema,
  updateSettingsInput,
} from "@/types/settings";
import { settingsRepository, SETTINGS_SINGLETON_ID } from "@/storage/settings";

const recipeRouter = router({
  /** Return every stored recipe. */
  list: procedure.output(z.array(recipeSchema)).query(async () => {
    return recipeRepository.getAll();
  }),

  /** Return a single recipe by ID (throws if not found). */
  getById: procedure
    .input(z.object({ id: z.string() }))
    .output(recipeSchema)
    .query(async ({ input }) => {
      const recipe = await recipeRepository.getById(input.id);
      if (!recipe) {
        throw new Error(`Recipe not found: ${input.id}`);
      }
      return recipe;
    }),

  /** Create a new recipe. ID and timestamps are generated by the repository. */
  create: procedure
    .input(createRecipeInput)
    .output(recipeSchema)
    .mutation(async ({ input }) => {
      return recipeRepository.create(input);
    }),

  /** Partially update an existing recipe. */
  update: procedure
    .input(updateRecipeInput)
    .output(recipeSchema)
    .mutation(async ({ input }) => {
      const updated = await recipeRepository.update(input);
      if (!updated) {
        throw new Error(`Recipe not found: ${input.id}`);
      }
      return updated;
    }),

  /** Delete a recipe by ID. Returns `true` on success. */
  delete: procedure
    .input(z.object({ id: z.string() }))
    .output(z.object({ success: z.boolean() }))
    .mutation(async ({ input }) => {
      const deleted = await recipeRepository.delete(input.id);
      return { success: deleted };
    }),
});

const settingsRouter = router({
  /** Return the singleton settings object. Auto-creates with defaults if none exists. */
  get: procedure.output(settingsSchema).query(async () => {
    const existing = await settingsRepository.getById(SETTINGS_SINGLETON_ID);
    if (existing) return existing;
    return settingsRepository.create({});
  }),

  /** Update the singleton settings. */
  update: procedure
    .input(updateSettingsInput)
    .output(settingsSchema)
    .mutation(async ({ input }) => {
      const updated = await settingsRepository.update(input);
      if (!updated) {
        throw new Error(`Settings not found: ${input.id}`);
      }
      return updated;
    }),
});

export const appRouter = router({
  recipe: recipeRouter,
  settings: settingsRouter,
});

export type AppRouter = typeof appRouter;
